export type IconNameT =
  | "12-hours"
  | "123"
  | "activity"
  | "bone"
  | "cat"
  | "chevron-down"
  | "chevron-right"
  | "clipboard-heart"
  | "components"
  | "dog-bowl"
  | "dog"
  | "news"
  | "shopping-cart"
  | "stethoscope"
  | "user-circle"
  | "zeppelin-off"
  | "zeppelin"
  | "zip"
  | "zodiac-aquarius"
  | "zodiac-aries"
  | "zodiac-cancer"
  | "zodiac-capricorn"
  | "zodiac-gemini"
  | "zodiac-leo"
  | "zodiac-libra"
  | "zodiac-pisces"
  | "zodiac-sagittarius"
  | "zodiac-scorpio"
  | "zodiac-taurus"
  | "zodiac-virgo"
  | "zoom-cancel"
  | "zoom-check-filled"
  | "zoom-check"
  | "zoom-code"
  | "zoom-exclamation"
  | "zoom-filled"
  | "zoom-in-area-filled"
  | "zoom-in-area"
  | "zoom-in-filled"
  | "zoom-in"
  | "zoom-money"
  | "zoom-out-area"
  | "zoom-out-filled"
  | "zoom-out"
  | "zoom-pan"
  | "zoom-replace"
  | "zoom-reset"
  | "zoom-scan"
  | "zzz-off"
  | "zzz";

export interface IconI {
  name: IconNameT;
  color?: string;
  size?: number | string;
  stroke?: number | string;
}
